language: ruby
rvm:
  - 1.9.3
script:
  - bundle exec bundle-audit check --update
  - bundle exec rake test
notifications:
  email:
    recipients:
      - healthcare-ci@googlegroups.com
    on_failure: change

branches: 
  only:
    - master
    - bonnie-prior
    - bonnie-prior_1302_nokogiri_fix
